controller:
  image:
    repository: controller
    tag: v1.1.1-alpha-lua-keepalive
    # pullPolicy: Always
    digest: ""
  ingressClassResource:
    name: nginx
    controllerValue: k8s.io/ingress-nginx
    enabled: true
    default: true